version: '3.8'

services:
  lobby-frontend:
    image: lobby-frontend
    container_name: 'Goc-Lobby-Frontend'
    ports:
      - "4201:4200"

  lobby-backend:
    build:
      context: ./lobby-backend
    container_name: 'Goc-Lobby-Backend'
    ports:
      - "8081:8080"
