version: '3.8'

services:
  lobby-frontend:
    image: goc-lobby-frontend:0.1.0
    container_name: 'Goc-Lobby-Frontend'
    ports:
      - "4201:4200"

  lobby-backend:
    image: goc-lobby-backend:0.1.0
    container_name: 'Goc-Lobby-Backend'
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - LOBBY_FRONTEND_URL=${LOBBY_FRONTEND_URL:-http://localhost:4201}
