version: '3.8'

services:
  lobby-frontend:
    image: lobby-frontend
    container_name: 'Goc-Lobby-Frontend'
    ports:
      - "4201:4200"

  lobby-backend:
    build:
      context: ./lobby-backend
    container_name: 'Goc-Lobby-Backend'
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME} 
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
